### ISSUE TITLE
Use environment variable COMPOSER_HOME for default values instead of $HOME/.composer

### ISSUE THREAD

**Issue by derimagia** [consolidation/cgr#10]
Current it uses `$HOME/.composer` as the default value for prefix path for the default paths. I think it would make more sense to have this default to `COMPOSER_HOME` if it is set, and fallback otherwise.

See https://getcomposer.org/doc/03-cli.md#composer-home

Currently a minor issue when setting up a docker container with it from the [official composer](https://hub.docker.com/_/composer/) as it [defaults the path to /composer](https://github.com/composer/docker/blob/f9ee1f61cad16269132e24e93f08e60915b9f431/1.2/Dockerfile#L10).

**Comment by mikeshiyan** [comment]
Also some systems (like my Linux Mint 18) have default Composer home in ~/.config/composer

**Comment by mikeshiyan** [comment]
As a workaround for this issue env vars can be used:
```
export CGR_BASE_DIR="$HOME/.config/composer/global"
export CGR_BIN_DIR="$HOME/.config/composer/vendor/bin"
```

**Comment by ShaoZeMing** [comment]
你好，我执行 
`composer global require consolidation/cgr`
,安装成功了，可是运行时却没有cgr 指令。是不是必须要添加？

```
export CGR_BASE_DIR="$HOME/.config/composer/global"
export CGR_BIN_DIR="$HOME/.config/composer/vendor/bin"
```
???

**Comment by greg-1-anderson** [comment]
@ShaoZeMing: Make sure that your `bin` directory also appears in your `$PATH`.

**Comment by greg-1-anderson** [comment]
This is a very good idea.

**Comment by javi-dev** [comment]
Thanks, it works now on my Ubuntu system that uses ~/.config/composer by default, as @mikeshiyan mentioned. I had to export the variable myself on my .zshrc though, (`export COMPOSER_HOME="$HOME/.config/composer/"`); Composer didn't configure it on its own, for some reason.

I think this should be added to the documentation, otherwise cgr wouldn't work out of the box on systems like mine. Maybe in "Installation and Usage", "cgr will try to use the $COMPOSER_HOME environment variable, and fallback to $HOME/.composer if not found", or something like that. It's also missing from the environment variables table now.

**Comment by greg-1-anderson** [comment]
Hm, I thought that `COMPOSER_HOME` would be defined in that instance. Is '$XDG_CONFIG_HOME' defined on your system? See the [COMPOSER_HOME](https://getcomposer.org/doc/03-cli.md#composer-home) documentation.

**Comment by greg-1-anderson** [comment]
I suggest adding the following text under the environment variables table:

> If these variables are not defined, then cgr uses the value of the `COMPOSER_HOME` environment variable as the base directory to use as described in the [Composer documentation on environment variables](https://getcomposer.org/doc/03-cli.md#composer-home).

We'd also need to change the behavior appropriately. Would that work for you? If `$XGD_CONFIG_HOME` is not defined, then we might need to add another heuristic. It doesn't really matter _too much_ where the `global` directory is stored, as long as the `bin` directory is right.

**Comment by derimagia** [comment]
Looks like this is what we need to do?

https://github.com/composer/composer/blob/14c77130e8f717ceb154720e1abefafe99124cb9/src/Composer/Factory.php#L54

**Comment by javi-dev** [comment]
> Hm, I thought that COMPOSER_HOME would be defined in that instance. Is '$XDG_CONFIG_HOME' defined on your system? See the COMPOSER_HOME documentation.

> It does look like it's set up where if you have any of the 'XDG' variables (even if not $XDG_CONFIG_HOME) you get a different directory.

Thanks. I have several $XDG_* variables, but no $XDG_CONFIG_HOME. Could be something I messed up, but doing a quick googling around, it seems that Ubuntu doesn't follow the convention, even if it uses the .config/ directory to store these things, so the $XDG variables I have, they come from elsewhere.

Anyways, setting the proper $COMPOSER_HOME should probably be an issue for the Composer project. It doesn't hurt to warn users about it in the docs, so people don't have to read the code or find this issue. Having additional checks in the code wouldn't hurt either, as @derimagia said.

> If these variables are not defined, then cgr uses the value of the COMPOSER_HOME environment variable as the base directory to use as described in the Composer documentation on environment variables.

That's perfect.

**Comment by derimagia** [comment]
Don't think it's an issue with composer, usually applications don't set the environment variable, they only use it as a default... And it wouldn't work anyway if the user didn't run composer.

**Comment by greg-1-anderson** [comment]
@ javi-dev  Could you let me know if https://github.com/consolidation/cgr/pull/17 works on your system?

**Comment by greg-1-anderson** [comment]
PR merged -- thanks for the feedback
