### ISSUE TITLE
Install same package with different versions

### ISSUE THREAD

**Issue by mnabialek** [consolidation/cgr#14]
Is it possible to install package in 2 (or more) different versions? Normally it's not used too often but there are some packages that you would like to use in 2 different versions.

As example I would give you https://github.com/FriendsOfPHP/PHP-CS-Fixer - there is 1 and 2 version with drastic changes. For some of my projects I need to use version 1, and for new ones I need to use version 2. I've ended installing version 1 using cgr and installing version 2 using ordinary composer global require but it would be great of both could be achieved using cgr

**Comment by greg-1-anderson** [comment]
Currently, cgr determines the target installation folder solely by the github org and name of the project being installed. Also, regardless of the target installation folder, every project that is installed via `cgr` shares the same global vendor bin directory, and this global vendor bin directory is the same global vendor bin directory used by `composer global require`. For most projects, if you installed two different versions of the same project, they would still use the same binary name, and therefore would still conflict in the `./composer/vendor/bin` directory.

If you look at the [Installation and Usage](https://github.com/consolidation/cgr#installation-and-usage) section, you will see that you can use options &/or environment variables to change the target install location and the target bin directory location. If version 1 and version 2 of PHP CS Fixer use different binary names (as your report above implies -- I have not confirmed), then it would be sufficient to relocate only the installation target (`--base-dir`). If you wanted to install two versions of a tool that used the same binary name across all versions, then you would also need to set `--bin-dir`, and add this directory to your `$PATH`. At this point, you might as well just make your own install location and install via `composer require`.

For tools such as PHP-CS-Fixer, though, I think it is generally better to install a project-local copy via `composer require --dev`, and then run it via `composer exec`, or a Composer script. See [consolidation/annotated-command](https://github.com/consolidation/annotated-command) for an example of how this is done with phpcbf.
