### ISSUE TITLE
Update required packages

### ISSUE THREAD

**Issue by axel-rutz** [consolidation/cgr#18]
Use case:
* `cgr foo/bar # which requires foo/baz`
* drop foo/baz dependency or publish new foo/baz release
* `cgr update foo/bar`
  internally does:
  `composer '--working-dir=~/.composer/global/foo/bar' 'update' 'foo/bar'`
  so does NOT touch foo/baz

Workaround:
* `composer '--working-dir=~/.composer/global/foo/bar' 'update'`

**Comment by greg-1-anderson** [comment]
I agree - cgr should not include the project parameter when the operation is `update`.

**Comment by axel-rutz** [comment]
Greg you rock!
