### ISSUE TITLE
Cannot install cgr

### ISSUE THREAD

**Issue by shadtek** [consolidation/cgr#26]
I cannot install cgr. First what I've done:
1. Follow steps on https://getcomposer.org/download/
2. composer -v "Composer version 1.6.2 2018-01-05 15:28:41"
3. composer global require consolidation/cgr
4. $ cgr
-bash: cgr: command not found

**Comment by greg-1-anderson** [comment]
From the `cgr` README:

> If you have not already done so, you will also need to add ~/.composer/vendor/bin to your $PATH. Thereafter, you may subsitute cgr for any commandline tool whose installation instructions recommends the use of Composer global require.

**Comment by greg-1-anderson** [comment]
Side note: The last half of the text I quoted is out-of-date. Early versions of cgr called through to `composer` for any command that cgr did not handle itself. That feature was removed, though, so you may not simply substitute cgr for any composer command - only use it for those commands supported by cgr, e.g. `cgr require`

**Comment by shadtek** [comment]
export PATH="$HOME/.composer/vendor/bin:$PATH"
^ Already in my .bashrc
echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

That looks bad right?

**Comment by greg-1-anderson** [comment]
`which cgr` does not return the path to cgr?

Is there anything in `~/.composer/vendor/bin`? Some platforms put the binaries in `~/.config/composer/vendor/bin` or something of that sort.

**Comment by shadtek** [comment]
`cgr  laravel` are listed in `~/.composer/vendor/bin`
`cd .config`
`-bash: cd: .config: No such file or directory`

**Comment by shadtek** [comment]
A reinstall of macOS High Sierra and a software update seems to have fixed the issue with cgr, thanks for following up Greg Anderson.
