### ISSUE TITLE
Possible to install Drush 8 with cgr?

### ISSUE THREAD

**Issue by aangelinsf** [consolidation/cgr#27]
I require both Drush 8 and 9. 

I just tried cgr drush/drush:8.x and it did not work.

composer global require drush/drush:8.x still works fine, so I used that and made a soft link for "drush8" in .composer/vendor/bin.

But it would be handy if CGR could install Drush 8 with its method inside of the global directory. (Great tool, btw.)

**Comment by greg-1-anderson** [comment]
The following worked for me:

- cgr drush/drush:8.x-dev
- cgr drush/drush:^8

If cgr is not working for some reason, using the workaround described at the bottom of the README is preferable to using `composer global`.

**Comment by aangelinsf** [comment]
@greg-1-anderson, that seems to blow away Drush 9. Possible to install both with this?

**Comment by greg-1-anderson** [comment]
Well, cgr installs each project in a directory named after the org and project, and both Drush 8 and Drush 9 are drush-ops/drush. I'd recommend using [the workaround recommended in the README](https://github.com/consolidation/cgr#manual-use-of-native-composer-features). Create a directory somewhere (anywhere) for Drush 8, and another for Drush 9, and run that composer require command for ^8 and ^9 respectively in each
