### ISSUE TITLE
Install for all users?

### ISSUE THREAD

**Issue by donquixote** [consolidation/cgr#30]
So far I have always installed cgr commands in my home directory, `~/.composer`.
This means the commands are only available to me.

Is there a recommended way to do it system-wide for all users?
So.
- Install composer globally for all users
- Install cgr globally for all users.
- Let cgr install all commands globally for all users.

I might figure this out if I tried a little harder.. but I think it does make sense to document a recommended / standard way of doing this.

**Comment by donquixote** [comment]
> Install composer globally for all users

I think the common way to install composer already makes it available globally to all users.
E.g. like this, https://www.digitalocean.com/community/tutorials/how-to-install-and-use-composer-on-ubuntu-14-04

> Install cgr globally for all users.
> Let cgr install all commands globally for all users.

I found this, https://stackoverflow.com/a/33381090/246724
But so far it is not working.

**Comment by greg-1-anderson** [comment]
cgr is a pretty simple program. As long as it is chmod +x for all users and exists in a global $PATH, it will work.

The details of managing the global $PATH, install location and owning user for global commands may vary from platform to platform and is beyond the scope of the documentation for this project.

**Comment by donquixote** [comment]
For anyone coming here:
I managed to make it work, basically following https://stackoverflow.com/a/33381090/246724

I put this in `/etc/environment`:

    PATH="[..]:/usr/local/composer/vendor/bin"
    COMPOSER_HOME="/usr/local/composer"
