### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by ghost** [consolidation/cgr#40]
Hello friend,

Have you plans to accept php 8 in requirements?

**Comment by greg-1-anderson** [comment]
I have been working my way through the php 8 updates of the consolidation components, but only got partway through and currently do not have a lot of time for open source work. This one will probably just work. PRs welcome.

**Comment by nB-Hylid** [comment]
Who (else) can review PR in #41 ?

**Comment by greg-1-anderson** [comment]
I'll merge with any +1 from the community verifying correct behavior on php8

**Comment by dpi** [comment]
As reported on https://github.com/dpi/dogit/issues/6#issue-953179390, the project seems to work just fine by using ignore-platform-reqs. So it seems these minor composer.json changes in the PR are unlikely to break things.

**Comment by SanderWind** [comment]
For people who want to install without this PR merged yet:

`composer global require --ignore-platform-req php consolidation/cgr`

**Comment by hswong3i** [comment]
For your reference finally I give up with cgr, but shift to OBS based (https://build.opensuse.org) deb/rpm management, e.g.:
* Package `composer/composer` in deb/rpm (see https://github.com/alvistack/composer-composer/commit/7866c2ca493a1d13bf189b1ed833aad3e873d865 commit message)
* During packaging, similar as cgr, create a global isolated install directory under `/usr/share/php/vendor` (see https://github.com/alvistack/composer-composer/commit/7866c2ca493a1d13bf189b1ed833aad3e873d865#diff-889c5495b68d2a0c0d1f238818716a71939918499efbc0fc6d2994319624fc67R7-R17)
* Once installed, symlink the executable from `/usr/share/php/vendor/composer/bin/composer composer` to `/usr/bin/composer`
* Once local build completed, push it to OBS for building deb/rpm on supported OS (see https://build.opensuse.org/package/show/home:alvistack/composer-composer-2.3.10)
* Now we could install the result deb/rpm directly, e.g. https://download.opensuse.org/repositories/home:/alvistack/xUbuntu_22.04/all/composer_2.3.10-1_all.deb

Some other else example:
* https://github.com/alvistack/sebastianbergmann-phpunit/commit/70cd3a89e8162714ad5963ba9f1ec44f4f2c89ed
* https://github.com/alvistack/FriendsOfPHP-PHP-CS-Fixer/commit/73e65255cb15fc7e434e748f6d44a814730af6b5
* https://github.com/alvistack/squizlabs-PHP_CodeSniffer/commit/bfa09aec4fb0c7c527ff35bdcbd53e200aa056ce

**Comment by darrenoh** [comment]
> I'll merge with any +1 from the community verifying correct behavior on php8

Cgr works with PHP 8.1.

**Comment by greg-1-anderson** [comment]
No one put the +1 on the PR, looks like I missed over a year of +1's over here on the issue. Not being pedantic, I just get a lot of GitHub notifications and didn't notice. Going to go merge the PR now.

**Comment by EHLOVader** [comment]
This appears to be merged but not published. 
Do we need to install 2.x-dev instead of the latest which is 2.0.5?

**Comment by greg-1-anderson** [comment]
Forgot to tag a release. Tagged 2.0.6.

**Comment by EHLOVader** [comment]
perfect, thank you!
